spring.application.name=WebService_Uppgifter_Lektion_8
# HTTPS
server.port=8443
server.ssl.key-store=classpath:mykeystore.p12
server.ssl.key-store-password=Benny123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mycert

# Redirect HTTP → HTTPS
server.http.port=8080
server.http.redirect-to-https=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect